cryticArgs: ["--solc-remaps", "@openzeppelin/=/workspaces/Matchbox/node_modules/@openzeppelin/"]
testMode: "assertion"
testLimit: 500000
deployContracts: [["0xc1FDdD8C8E57a10419A01b1aEC2f4F4F64A2393f", "RaceTest"]]
balanceContract: 1000000000000000000000
testMaxGas: 1000000000
